// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0KIKZz4e6OVFUXntoi3tw3aBKILoIElY',
    appId: '1:714106175491:web:9c8bebf75f7b7e626fce36',
    messagingSenderId: '714106175491',
    projectId: 'asistencia-qr-68c24',
    authDomain: 'asistencia-qr-68c24.firebaseapp.com',
    storageBucket: 'asistencia-qr-68c24.firebasestorage.app',
    measurementId: 'G-KXP4MZ40Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnC5PpQvdmUgmciIfxxeW1lr2g82z8lyU',
    appId: '1:714106175491:android:3399fa0408ea41696fce36',
    messagingSenderId: '714106175491',
    projectId: 'asistencia-qr-68c24',
    storageBucket: 'asistencia-qr-68c24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD42fZSvHC7TUpYs6df3dCOOvs93CNxl80',
    appId: '1:714106175491:ios:3f9ae0612f6938596fce36',
    messagingSenderId: '714106175491',
    projectId: 'asistencia-qr-68c24',
    storageBucket: 'asistencia-qr-68c24.firebasestorage.app',
    iosClientId: '714106175491-b906si7pcfpf2jqp6l1poiu6lm274hd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.asistenciaQr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD42fZSvHC7TUpYs6df3dCOOvs93CNxl80',
    appId: '1:714106175491:ios:3f9ae0612f6938596fce36',
    messagingSenderId: '714106175491',
    projectId: 'asistencia-qr-68c24',
    storageBucket: 'asistencia-qr-68c24.firebasestorage.app',
    iosClientId: '714106175491-b906si7pcfpf2jqp6l1poiu6lm274hd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.asistenciaQr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0KIKZz4e6OVFUXntoi3tw3aBKILoIElY',
    appId: '1:714106175491:web:9c8bebf75f7b7e626fce36',
    messagingSenderId: '714106175491',
    projectId: 'asistencia-qr-68c24',
    authDomain: 'asistencia-qr-68c24.firebaseapp.com',
    storageBucket: 'asistencia-qr-68c24.firebasestorage.app',
    measurementId: 'G-KXP4MZ40Q1',
  );
}
